# https://www.home-assistant.io/integrations/default_config/
default_config:

logger:
  default: warn
  logs:
    custom_components.ml_model_controller_integration.sensor: debug
    homeassistant: warn
